.TH "/home/michel/workspace/LZ5/alelo.h" 3 "Terça, 29 de Janeiro de 2013" "Version lz5_turbo" "LZ5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/michel/workspace/LZ5/alelo.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBAlelo\fP"
.br
.RI "\fIClasse para criar um \fBAlelo\fP\&. \fP"
.ti -1c
.RI "class \fBAleloId\fP"
.br
.RI "\fIClasse derivada para criar um \fBAlelo\fP com sua identificacao (ID)\&. \fP"
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para LZ5 a partir do código fonte\&.
