.TH "/home/michel/workspace/LZ5/geracao.h" 3 "Terça, 29 de Janeiro de 2013" "Version lz5_turbo" "LZ5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/michel/workspace/LZ5/geracao.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'individuo\&.h'\fP
.br

.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBGeracao\fP"
.br
.RI "\fICria uma \fBGeracao\fP que ira constituir uma populacao\&. \fP"
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para LZ5 a partir do código fonte\&.
