.TH "/home/michel/workspace/LZ5/individuo.cpp" 3 "Terça, 29 de Janeiro de 2013" "Version lz5_turbo" "LZ5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/michel/workspace/LZ5/individuo.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <gsl/gsl_rng\&.h>\fP
.br
\fC#include <gsl/gsl_randist\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'individuo\&.h'\fP
.br

.SS "Variáveis"

.in +1c
.ti -1c
.RI "gsl_rng * \fBp\fP"
.br
.in -1c
.SH "Documentação das variáveis"
.PP 
.SS "gsl_rng* \fBp\fP"
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para LZ5 a partir do código fonte\&.
