.TH "/home/michel/workspace/LZ5/loco.h" 3 "Terça, 29 de Janeiro de 2013" "Version lz5_turbo" "LZ5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/michel/workspace/LZ5/loco.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'alelo\&.h'\fP
.br

.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBLoco\fP"
.br
.RI "\fIClasse para criar um \fBLoco\fP a partir de 2 Alelos\&. \fP"
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para LZ5 a partir do código fonte\&.
