.TH "/home/michel/workspace/LZ5/loco.cpp" 3 "Terça, 29 de Janeiro de 2013" "Version lz5_turbo" "LZ5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/michel/workspace/LZ5/loco.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'loco\&.h'\fP
.br

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para LZ5 a partir do código fonte\&.
